### PR TITLE
My final version for this project. Thanks for any critique!

### PR DESCRIPTION
**Pull request by jacobbria**
Thanks for any help!

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@jacobbria Hi! Thanks for submitting! It looks like your project was already a repository itself so it was picked up as a subfolder. You can see what files were recognized by git in the "Filers Changed" tab: 

image

To fix this, remove the .git folder from inside your project folder (not the academy's folder), commit again and push 😁 Let me know if you have questions

**Comment by TheCSharpAcademy** [comment]
@jacobbria Let us know if you need help? 😄

**Comment by TheCSharpAcademy** [comment]
@jacobbria It's been two weeks since the suggested changes, so we're archiving this project. Feel free to reopen the PR and resubmit in the academy when you're ready. 🤓

**Comment by jacobbria** [comment]
> @jacobbria It's been two weeks since the suggested changes, so we're archiving this project. Feel free to reopen the PR and resubmit in the academy when you're ready. 🤓

Hey I am so sorry I just now got to reading the critiques. 
I did not see any notifications on GitHub, my mistake. 

I have some exams and interviews coming up, after which I plan to make the edits and continue.

**Pull request closed without merging**
