### PR TITLE
Project Finished!

### PR DESCRIPTION
**Pull request by CarDioLogic**
Best regards, JMS

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@CarDioLogic The project is looking great! I really like your styling changes and I See you added difficulty levels too!

Now I'm getting an error where I can't save the game and it says the table doesn't exist. Is that happening with you too?

image

**Comment by CarDioLogic** [comment]
Ok, it seems i am having a weird issue. When i try to run the app while inside my local repository this happens:
Capturar

If i copy my project folder outside my local repository (for ex: to my desktop area) and try to run the app... it runs without any issues and everything is working (I am able to save my games and see the table, no issues).

I don't understand what is causing this yet. The App only works as intented if the project folder is located outside the local repository!

**Comment by TheCSharpAcademy** [comment]
@CarDioLogic Sorry I forgot to reply. I'm not sure what causes that either. Would you mind fixing it outside the repo and copying into the repo again so I can finish this review? 😁

**Comment by CarDioLogic** [comment]
That's is the strange thing. The app is working normally outside the repo... it allows the user to do everything (play the game, the records are properly saved, the user can see them, can delete them, etc. Everything is working fine when i copy it outside the repo).

I even had my backup project folder saved locally. I tried deleting the local repo and cloning it again, then deleting everything inside it and copying my backup project folder into the local repo, and as soon as i try to run the app from inside the local repo it simply does not run. And it gives the error i have shown above...

I dont know if its caused by different filepaths or anything, i tried many different things but i just cant get it to work while it is stored inside the repo :(
I even tried using chatGPT by showing it the error message, but i just could not figure it out..yet.

But im starting to wonder if it isnt just better to delete everything and do it all over from scratch? I would try to rebuild the app to be basically the same and hopefully this error would not appear again. Would that be better? -

**Comment by CarDioLogic** [comment]
Basically, the app does not run at all while inside the repo. But if it is outside, there are no problems at all.

**Comment by TheCSharpAcademy** [comment]
@CarDioLogic Just make sure it works locally for you, then upload to the repo and commit, and I'll deal with it from there. How does that sound?

**Comment by TheCSharpAcademy** [comment]
@CarDioLogic Well done! We got there in the end haha

**Comment by CarDioLogic** [comment]
True, thank god ahah I dont what caused some of those errors but its done :P

**Pull request merged**
