### PR TITLE
DreamFXX - MathGame project finished

### PR DESCRIPTION
**Pull request by DreamFXX**
I just completely finished my mathGame learning project. I will be waiting for your review, had a great time writing it,

Have a nice day!

DreamFXX

### CODE REVIEW

**Review by DreamFXX — COMMENTED** [review]
Waiting for the review.. :)

**Review by DreamFXX — COMMENTED** [review]
- Revision?

**Comment by TheCSharpAcademy** [comment]
@DreamFXX Hey! Do you still want it to be reviewed? 😄

**Comment by DreamFXX** [comment]
> @DreamFXX Hey! Do you still want it to be reviewed? 😄

Yes.

**Pull request closed without merging**
